### ISSUE TITLE
while performing on the frontend folder after dong npm install ./node_modules/.bin/webpack --config webpack.config.js --watch throws this error

### ISSUE THREAD

**Issue by githubniraj** [CodecoolBP20161/advanced-module-sherwood-bet#20]
Error: Cannot find module 'C:\DependenciesMVN\advanced-module-sherwood-bet-wd-module-sherwood-bet\frontend\webpack.config.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at module.exports (C:\DependenciesMVN\advanced-module-sherwood-bet-worksdule-sherwood-bet\frontend\node_modules\webpack\bin\convert-argv.js:80:13)
    at Object.<anonymous> (C:\DependenciesMVN\advanced-module-sherwood-bet-wd-module-sherwood-bet\frontend\node_modules\webpack\bin\webpack.js:39:40)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
bash: module.js:472: command not found

**Comment by tbalint19** [comment]
I guess it is because the source code for some apps are not provided here at all.
This is a tiny opensource "slice" of the actual project that is being developed (not in this repo).
Anyways, if you are here to check out one example of the many out there of how reactJS is used with redux, I recommend you to check out this boilerplate of mine, which has less dependencies.
https://github.com/tbalint19/React-ES6-Redux-boilerplate
I am more or less sure it is not "the best" practice, but a pretty good one for sure.

**Comment by githubniraj** [comment]
It did not clear me, can you update this code in this project specifically to throw the above error, i tried to resolve by looking at your link for boilerplate code but no progress. Thanks in advance.

**Comment by githubniraj** [comment]
It did not clear me, can you update this code in this project specifically to throw the above error, i tried to resolve by looking at your link for boilerplate code but no progress. Thanks in advance.
